In [2]:
import pandas as pd

In [21]:
df = pd.read_csv("C:\\Users\\jaime\\OneDrive\\Downloads\\archive (1)\\BraTS2020_training_data\\content\\data\\meta_data.csv")
labels = df["target"].values
paths = df["slice_path"].values
df

                                  slice_path  target  volume  slice
0         /content/data/volume_41_slice_0.h5       0      41      0
1         /content/data/volume_41_slice_1.h5       0      41      1
2         /content/data/volume_41_slice_2.h5       0      41      2
3         /content/data/volume_41_slice_3.h5       0      41      3
4         /content/data/volume_41_slice_4.h5       0      41      4
...                                      ...     ...     ...    ...
57190  /content/data/volume_241_slice_150.h5       0     241    150
57191  /content/data/volume_241_slice_151.h5       0     241    151
57192  /content/data/volume_241_slice_152.h5       0     241    152
57193  /content/data/volume_241_slice_153.h5       0     241    153
57194  /content/data/volume_241_slice_154.h5       0     241    154

[57195 rows x 4 columns]

In [22]:
df['slice_path'] = df['slice_path'].apply(lambda x: x.replace('/content/data/', ''))
df['slice_path'] = df['slice_path'].apply(lambda x: x.replace('.h5', ''))
df.drop(columns=['volume','slice'], inplace=True)
df

                 slice_path  target
0         volume_41_slice_0       0
1         volume_41_slice_1       0
2         volume_41_slice_2       0
3         volume_41_slice_3       0
4         volume_41_slice_4       0
...                     ...     ...
57190  volume_241_slice_150       0
57191  volume_241_slice_151       0
57192  volume_241_slice_152       0
57193  volume_241_slice_153       0
57194  volume_241_slice_154       0

[57195 rows x 2 columns]

In [24]:
df.to_csv("C:\\Users\\jaime\\OneDrive\\Downloads\\archive (1)\\MU-Diff images\\meta_data.csv", index=False)

In [26]:
new_df = pd.read_csv("C:\\Users\\jaime\\OneDrive\\Downloads\\archive (1)\\MU-Diff images\\meta_data.csv")
new_df

                 slice_path  target
0         volume_41_slice_0       0
1         volume_41_slice_1       0
2         volume_41_slice_2       0
3         volume_41_slice_3       0
4         volume_41_slice_4       0
...                     ...     ...
57190  volume_241_slice_150       0
57191  volume_241_slice_151       0
57192  volume_241_slice_152       0
57193  volume_241_slice_153       0
57194  volume_241_slice_154       0

[57195 rows x 2 columns]